name: Minetrends
version: ${project.version}
website: ${project.url}
authors: [NXTGUY, VolcanicPlaza, Packet]

main: com.volcanicplaza.minetrends.Minetrends
database: false

commands:
  minetrends:
    descrption: Main command for the Minetrends plugin.
    aliases: [minet, mtrends, mt]
