name: Minetrends
version: ${project.version}
website: ${project.url}
authors: [NXTGUY, VolcanicPlaza, Packet]

depend: [Lib]

main: com.volcanicplaza.minetrends.Minetrends
database: false

commands:
  minetrends:
    descrption: Minetrends management command.
    aliases: [mtrends]
