name: Minetrends
version: 1.4.1
website: Minetrends.com
author: NXTGUY & VolcanicPlaza

main: com.volcanicplaza.Minetrends.Minetrends
database: false

commands:
  minetrends:
    descrption: Main command for the Minetrends plugin.
    aliases: [minet, mtrends]
